# Generated by Django 3.2 on 2024-12-20 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleGenre',
            new_name='GenreTitle',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'default_related_name': 'genres', 'ordering': ['-id'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='genretitle',
            options={'ordering': ('id',), 'verbose_name': 'Жанры и произведения', 'verbose_name_plural': 'Таблица жанров и произведений'},
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0, message='Неккоректное значение - год не может быть до н.э.'), django.core.validators.MaxValueValidator(2024, message='Неккоректное значение - вы указыаете еще не наступивший год')], verbose_name='Год выхода'),
        ),
    ]
