# Generated by Django 3.2 on 2024-12-21 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_title_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'default_related_name': 'titles', 'ordering': ('-year', 'name'), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.MaxLengthValidator(256)], verbose_name='Название произведения'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0, message='Некорректное значение - год не может быть до н.э.'), django.core.validators.MaxValueValidator(2024, message='Некорректное значение - вы указыаете еще не наступивший год')], verbose_name='Год выхода'),
        ),
    ]
